<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Terms and Conditions</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <style>
        body {
            background-color: #f8f9fa;
            padding-top: 50px;
        }
        header {
            background-color: #007bff;
            color: #fff;
            text-align: center;
            padding: 20px;
            margin-bottom: 20px;
        }
        main {
            padding: 20px;
        }
        footer {
            text-align: center;
            padding: 20px;
            background-color: #f8f9fa;
            margin-top: 20px;
        }
        section {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
    <header>
        <h1>Terms and Conditions</h1>
    </header>
    <main>
        <section>
            <h2>Acceptance of Terms</h2>
            <p>By accessing and using the services provided by Medicio Medical Lab ("Medicio"), you agree to be bound by these Terms and Conditions, as well as any additional terms and conditions and policies referenced herein.</p>
        </section>
        <section>
            <h2>Services Offered</h2>
            <p>Medicio offers various healthcare services including medical tests, sample collection, consultations with doctors, and medical reports delivery. These services are subject to availability and may be modified or discontinued at any time without prior notice.</p>
        </section>
        <section>
            <h2>Appointment Booking</h2>
            <p>Users can book appointments for medical tests and consultations through the Medicio website or by calling the provided contact number during operational hours.</p>
        </section>
        <section>
            <h2>Package Selection</h2>
            <p>Users can choose from a variety of healthcare packages offered by Medicio, each covering different health symptoms. The prices and contents of these packages are subject to change without prior notice.</p>
        </section>
        <section>
            <h2>Medical Professionals</h2>
            <p>Medicio employs a range of qualified medical professionals, including doctors and specialists. The availability of specific doctors may vary and is subject to change without prior notice.</p>
        </section>
        <section>
            <h2>Privacy and Data Security</h2>
            <p>Medicio is committed to protecting the privacy and security of user information. Any personal data collected during the provision of services will be handled in accordance with our Privacy Policy.</p>
        </section>
        <section>
            <h2>Payment</h2>
            <p>Payment for services provided by Medicio must be made in full at the time of booking or as otherwise specified. Payment methods accepted may vary and are subject to change without prior notice.</p>
        </section>
        <section>
            <h2>Cancellation and Refunds</h2>
            <p>Users may cancel appointments or healthcare package bookings subject to the cancellation policy outlined at the time of booking. Refunds, if applicable, will be processed in accordance with our Refund Policy.</p>
        </section>
        <section>
            <h2>Medical Reports</h2>
            <p>Medical reports generated by Medicio are provided for informational purposes only and should not be considered as a substitute for professional medical advice. Users should consult with a qualified healthcare provider for diagnosis and treatment of any medical condition.</p>
        </section>
        <section>
            <h2>Limitation of Liability</h2>
            <p>Medicio shall not be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in any way connected with the use of its services, including but not limited to, any errors or omissions in the content, loss of data, or interruption of business.</p>
        </section>
        <section>
            <h2>Governing Law</h2>
            <p>These Terms and Conditions shall be governed by and construed in accordance with the laws of India. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts in India.</p>
        </section>
        <section>
            <h2>Changes to Terms</h2>
            <p>Medicio reserves the right to update or modify these Terms and Conditions at any time without prior notice. Users are encouraged to review this page periodically for any changes.</p>
        </section>
    </main>
    <footer>
        <!-- Add footer content here -->
    </footer>
</body>

</html>
